### ISSUE TITLE
执行python img2sgf.py 报错

### ISSUE THREAD

**Issue by skeras2** [noword/image2sgf#11]
你好，
clone代码后运行python img2sgf.py example\1.jpg，报如下错误：
Traceback (most recent call last):
  File "D:\Work\Workspace\git\Go\image2sgf\img2sgf.py", line 14, in demo
    img0, boxes0, scores0 = get_board_image(board_model, pil_img)
  File "D:\Work\Workspace\git\Go\image2sgf\img2sgf\tools.py", line 87, in get_board_image
    boxes, scores = get_board_position(board_model, img, expand)
  File "D:\Work\Workspace\git\Go\image2sgf\img2sgf\tools.py", line 78, in get_board_position
    assert [0] * 4 not in boxes
AssertionError
问题出在了哪里？

**Comment by skeras2** [comment]
解决了，模型没加载成功
