### ISSUE TITLE
Why this style gameboard cannot recgonize

### ISSUE THREAD

**Issue by ebizmis** [noword/image2sgf#5]
download image [here](http://www.ebizmis.com/7.jpg)

**Comment by noword** [comment]
![QQ截图20231014093748](https://github.com/noword/image2sgf/assets/2698959/a05b6c95-653c-4a27-b1ad-a88bd0416d45)

可以正常识别啊？

**Comment by ebizmis** [comment]
我在LINUX（centos 7.9, cuda12.1, cudnn-8.9.5.29）下运行 python3 img2sgf.py --sgf_name 7.sgf 7.jpg出现错误：
Traceback (most recent call last):
  File "/home/fausten/a/image2sgf/img2sgf.py", line 131, in <module>
    img2sgf(img, args.sgf_name, args.save_images)
  File "/home/fausten/a/image2sgf/img2sgf.py", line 96, in img2sgf
    _img, _, scores = get_board_image(board_model, img)
  File "/home/fausten/a/image2sgf/img2sgf/tools.py", line 86, in get_board_image
    boxes, scores = get_board_position(board_model, img, expand)
  File "/home/fausten/a/image2sgf/img2sgf/tools.py", line 66, in get_board_position
    assert len(set(_labels)) >= 4
AssertionError

是有个侦测棋盘四个角的边界阀值要改吗？
运行其他的jpg是好的。比如python3 img2sgf.py --sgf_name 8.sgf 8.jpg，这个是好的。[下载8.jpg](http://www.ebizmis.com/8.jpg)

**Comment by ebizmis** [comment]
还有如果要用到nvdia的gpu，是不是要把model.py中cpu改成cuda？

**Comment by noword** [comment]
git更新后再试试，我之前是用img2sgf_gui.pyw测试的，两者逻辑有少许不同。

要用cuda的话，在
```
board_model = get_board_model()
stone_model = get_stone_model()
```
后加
```
device = torch.device('cuda') 
board_model.to(device)
stone_model.to(device)
```

**Comment by ebizmis** [comment]
更新程序后7.jpg这个问题解决了，但是用cuda的提示错误，难道安装的pytorch对cuda支持有问题？
1st perspective
Traceback (most recent call last):
  File "/home/fausten/image2sgf/img2sgf.py", line 112, in img2sgf
    img0, boxes0, scores0 = get_board_image(board_model, pil_img)
  File "/home/fausten/image2sgf/img2sgf/tools.py", line 86, in get_board_image
    boxes, scores = get_board_position(board_model, img, expand)
  File "/home/fausten/image2sgf/img2sgf/tools.py", line 59, in get_board_position
    target = board_model(T.ToTensor()(img).unsqueeze(0))[0]
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torchvision-0.17.0a0+f96deba-py3.9-linux-x86_64.egg/torchvision/models/detection/fcos.py", line 610, in forward
    features = self.backbone(images.tensors)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torchvision-0.17.0a0+f96deba-py3.9-linux-x86_64.egg/torchvision/models/detection/backbone_utils.py", line 57, in forward
    x = self.body(x)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torchvision-0.17.0a0+f96deba-py3.9-linux-x86_64.egg/torchvision/models/_utils.py", line 69, in forward
    x = module(x)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fausten/image2sgf/img2sgf.py", line 115, in img2sgf
    img0, boxes0, scores0 = get_board_image(board_model, pil_img, False)
  File "/home/fausten/image2sgf/img2sgf/tools.py", line 86, in get_board_image
    boxes, scores = get_board_position(board_model, img, expand)
  File "/home/fausten/image2sgf/img2sgf/tools.py", line 59, in get_board_position
    target = board_model(T.ToTensor()(img).unsqueeze(0))[0]
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torchvision-0.17.0a0+f96deba-py3.9-linux-x86_64.egg/torchvision/models/detection/fcos.py", line 610, in forward
    features = self.backbone(images.tensors)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torchvision-0.17.0a0+f96deba-py3.9-linux-x86_64.egg/torchvision/models/detection/backbone_utils.py", line 57, in forward
    x = self.body(x)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torchvision-0.17.0a0+f96deba-py3.9-linux-x86_64.egg/torchvision/models/_utils.py", line 69, in forward
    x = module(x)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/.pyenv/versions/image2sgf/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

**Comment by ebizmis** [comment]
找到解决办法了[https://discuss.pytorch.org/t/input-type-torch-floattensor-and-weight-type-torch-cuda-floattensor-should-be-the-same-or-input-should-be-a-mkldnn-tensor-and-weight-is-a-dense-tensor/152430](url)
